0 z" data/lemming.png" load-bitmap
1 z" data/drunkstreet.tiles.png" load-bitmap
2 z" data/testani.png" load-bitmap
3 z" data/drunk.sprite.png" load-bitmap
4 z" data/player.sprite.png" load-bitmap
5 z" data/grapple.png" load-bitmap
6 z" data/cars.png" load-bitmap
7 z" data/alley.zone.png" load-bitmap
8 z" data/bbq.zone.png" load-bitmap
9 z" data/depot.zone.png" load-bitmap
10 z" data/pizza.zone.png" load-bitmap
11 z" data/end.png" load-bitmap

 
0 z" data/hey.ogg" load-sample
1 z" data/sounds/alley1.ogg" load-sample
2 z" data/sounds/bbq1.ogg" load-sample
3 z" data/sounds/bbq2.ogg" load-sample
4 z" data/sounds/depot1.ogg" load-sample
5 z" data/sounds/depot2.ogg" load-sample
6 z" data/sounds/distraction1.ogg" load-sample
7 z" data/sounds/distraction2.ogg" load-sample
8 z" data/sounds/distraction3.ogg" load-sample
9 z" data/sounds/distraction4.ogg" load-sample
10 z" data/sounds/end1.ogg" load-sample
11 z" data/sounds/end2.ogg" load-sample
12 z" data/sounds/end3.ogg" load-sample
13 z" data/sounds/end4.ogg" load-sample
14 z" data/sounds/end5.ogg" load-sample
15 z" data/sounds/end6.ogg" load-sample
16 z" data/sounds/end7.ogg" load-sample
17 z" data/sounds/end8.ogg" load-sample
18 z" data/sounds/grab1.ogg" load-sample
19 z" data/sounds/grab2.ogg" load-sample
20 z" data/sounds/grab3.ogg" load-sample
21 z" data/sounds/grab4.ogg" load-sample
22 z" data/sounds/grab5.ogg" load-sample
23 z" data/sounds/pizza1.ogg" load-sample
24 z" data/sounds/pizza2.ogg" load-sample
25 z" data/sounds/pizza3.ogg" load-sample
26 z" data/sounds/ramble1.ogg" load-sample
27 z" data/sounds/ramble2.ogg" load-sample
28 z" data/sounds/ramble3.ogg" load-sample
29 z" data/sounds/sit1.ogg" load-sample
30 z" data/sounds/sit2.ogg" load-sample
31 z" data/sounds/sit3.ogg" load-sample
32 z" data/sounds/start1.ogg" load-sample
33 z" data/sounds/start2.ogg" load-sample
34 z" data/sounds/start3.ogg" load-sample